; Generated by tools/make_tables.py from orig/bomber.asm and orig/cgrom.bin - do not edit.

	defs (256 - ($ & 0FFh)) & 0FFh  ; the tables below are page aligned

; logical code -> tile address, game mode
game_tlo:
	defb low (tiles+0),low (tiles+16),low (tiles+32),low (tiles+48),low (tiles+64),low (tiles+80),low (tiles+96),low (tiles+112)
	defb low (tiles+128),low (tiles+144),low (tiles+160),low (tiles+160),low (tiles+176),low (tiles+176),low (tiles+192),low (tiles+208)
	defb low (tiles+224),low (tiles+240),low (tiles+256),low (tiles+272),low (tiles+288),low (tiles+304),low (tiles+256),low (tiles+320)
	defb low (tiles+336),low (tiles+224),low (tiles+160),low (tiles+160),low (tiles+176),low (tiles+176),low (tiles+352),low (tiles+352)
	defb low (tiles+176),low (tiles+368),low (tiles+384),low (tiles+400),low (tiles+384),low (tiles+416),low (tiles+416),low (tiles+400)
	defb low (tiles+432),low (tiles+448),low (tiles+432),low (tiles+464),low (tiles+464),low (tiles+176),low (tiles+176),low (tiles+176)
	defb low (tiles+480),low (tiles+496),low (tiles+512),low (tiles+528),low (tiles+464),low (tiles+528),low (tiles+512),low (tiles+544)
	defb low (tiles+560),low (tiles+528),low (tiles+464),low (tiles+576),low (tiles+464),low (tiles+592),low (tiles+432),low (tiles+464)
	defb low (tiles+608),low (tiles+608),low (tiles+624),low (tiles+608),low (tiles+640),low (tiles+608),low (tiles+640),low (tiles+656)
	defb low (tiles+672),low (tiles+688),low (tiles+704),low (tiles+672),low (tiles+704),low (tiles+688),low (tiles+704),low (tiles+688)
	defb low (tiles+640),low (tiles+624),low (tiles+624),low (tiles+720),low (tiles+624),low (tiles+736),low (tiles+736),low (tiles+752)
	defb low (tiles+768),low (tiles+784),low (tiles+624),low (tiles+752),low (tiles+768),low (tiles+752),low (tiles+768),low (tiles+800)
	defb low (tiles+816),low (tiles+832),low (tiles+848),low (tiles+864),low (tiles+816),low (tiles+832),low (tiles+848),low (tiles+864)
	defb low (tiles+816),low (tiles+832),low (tiles+848),low (tiles+864),low (tiles+384),low (tiles+400),low (tiles+464),low (tiles+544)
	defb low (tiles+880),low (tiles+896),low (tiles+912),low (tiles+928),low (tiles+880),low (tiles+896),low (tiles+912),low (tiles+928)
	defb low (tiles+880),low (tiles+896),low (tiles+912),low (tiles+928),low (tiles+944),low (tiles+960),low (tiles+560),low (tiles+576)
	defb low (tiles+976),low (tiles+960),low (tiles+400),low (tiles+432),low (tiles+448),low (tiles+432),low (tiles+448),low (tiles+464)
	defb low (tiles+992),low (tiles+1008),low (tiles+816),low (tiles+832),low (tiles+704),low (tiles+688),low (tiles+704),low (tiles+688)
	defb low (tiles+1024),low (tiles+1040),low (tiles+176),low (tiles+176),low (tiles+176),low (tiles+176),low (tiles+176),low (tiles+176)
	defb low (tiles+176),low (tiles+176),low (tiles+1056),low (tiles+1072),low (tiles+640),low (tiles+656),low (tiles+640),low (tiles+656)
	defb low (tiles+704),low (tiles+688),low (tiles+704),low (tiles+688),low (tiles+704),low (tiles+688),low (tiles+704),low (tiles+688)
	defb low (tiles+704),low (tiles+688),low (tiles+704),low (tiles+688),low (tiles+704),low (tiles+688),low (tiles+704),low (tiles+688)
	defb low (tiles+640),low (tiles+656),low (tiles+640),low (tiles+656),low (tiles+640),low (tiles+656),low (tiles+640),low (tiles+656)
	defb low (tiles+640),low (tiles+656),low (tiles+640),low (tiles+656),low (tiles+640),low (tiles+656),low (tiles+640),low (tiles+656)
	defb low (tiles+512),low (tiles+400),low (tiles+384),low (tiles+528),low (tiles+1088),low (tiles+1104),low (tiles+1120),low (tiles+1136)
	defb low (tiles+1152),low (tiles+1168),low (tiles+1184),low (tiles+1200),low (tiles+1216),low (tiles+1232),low (tiles+1248),low (tiles+1264)
	defb low (tiles+944),low (tiles+528),low (tiles+512),low (tiles+960),low (tiles+1280),low (tiles+1136),low (tiles+1088),low (tiles+1296)
	defb low (tiles+1312),low (tiles+1200),low (tiles+1152),low (tiles+1328),low (tiles+1344),low (tiles+1264),low (tiles+1216),low (tiles+1360)
	defb low (tiles+1376),low (tiles+1392),low (tiles+1408),low (tiles+1424),low (tiles+1424),low (tiles+1408),low (tiles+1440),low (tiles+1456)
	defb low (tiles+1472),low (tiles+1488),low (tiles+1504),low (tiles+1520),low (tiles+1536),low (tiles+1552),low (tiles+1504),low (tiles+1520)
	defb low (tiles+1568),low (tiles+1584),low (tiles+1600),low (tiles+1616),low (tiles+1616),low (tiles+1600),low (tiles+1632),low (tiles+1440)
	defb low (tiles+1648),low (tiles+1456),low (tiles+1536),low (tiles+1552),low (tiles+1552),low (tiles+1536),low (tiles+1536),low (tiles+1504)
game_thi:
	defb high (tiles+0),high (tiles+16),high (tiles+32),high (tiles+48),high (tiles+64),high (tiles+80),high (tiles+96),high (tiles+112)
	defb high (tiles+128),high (tiles+144),high (tiles+160),high (tiles+160),high (tiles+176),high (tiles+176),high (tiles+192),high (tiles+208)
	defb high (tiles+224),high (tiles+240),high (tiles+256),high (tiles+272),high (tiles+288),high (tiles+304),high (tiles+256),high (tiles+320)
	defb high (tiles+336),high (tiles+224),high (tiles+160),high (tiles+160),high (tiles+176),high (tiles+176),high (tiles+352),high (tiles+352)
	defb high (tiles+176),high (tiles+368),high (tiles+384),high (tiles+400),high (tiles+384),high (tiles+416),high (tiles+416),high (tiles+400)
	defb high (tiles+432),high (tiles+448),high (tiles+432),high (tiles+464),high (tiles+464),high (tiles+176),high (tiles+176),high (tiles+176)
	defb high (tiles+480),high (tiles+496),high (tiles+512),high (tiles+528),high (tiles+464),high (tiles+528),high (tiles+512),high (tiles+544)
	defb high (tiles+560),high (tiles+528),high (tiles+464),high (tiles+576),high (tiles+464),high (tiles+592),high (tiles+432),high (tiles+464)
	defb high (tiles+608),high (tiles+608),high (tiles+624),high (tiles+608),high (tiles+640),high (tiles+608),high (tiles+640),high (tiles+656)
	defb high (tiles+672),high (tiles+688),high (tiles+704),high (tiles+672),high (tiles+704),high (tiles+688),high (tiles+704),high (tiles+688)
	defb high (tiles+640),high (tiles+624),high (tiles+624),high (tiles+720),high (tiles+624),high (tiles+736),high (tiles+736),high (tiles+752)
	defb high (tiles+768),high (tiles+784),high (tiles+624),high (tiles+752),high (tiles+768),high (tiles+752),high (tiles+768),high (tiles+800)
	defb high (tiles+816),high (tiles+832),high (tiles+848),high (tiles+864),high (tiles+816),high (tiles+832),high (tiles+848),high (tiles+864)
	defb high (tiles+816),high (tiles+832),high (tiles+848),high (tiles+864),high (tiles+384),high (tiles+400),high (tiles+464),high (tiles+544)
	defb high (tiles+880),high (tiles+896),high (tiles+912),high (tiles+928),high (tiles+880),high (tiles+896),high (tiles+912),high (tiles+928)
	defb high (tiles+880),high (tiles+896),high (tiles+912),high (tiles+928),high (tiles+944),high (tiles+960),high (tiles+560),high (tiles+576)
	defb high (tiles+976),high (tiles+960),high (tiles+400),high (tiles+432),high (tiles+448),high (tiles+432),high (tiles+448),high (tiles+464)
	defb high (tiles+992),high (tiles+1008),high (tiles+816),high (tiles+832),high (tiles+704),high (tiles+688),high (tiles+704),high (tiles+688)
	defb high (tiles+1024),high (tiles+1040),high (tiles+176),high (tiles+176),high (tiles+176),high (tiles+176),high (tiles+176),high (tiles+176)
	defb high (tiles+176),high (tiles+176),high (tiles+1056),high (tiles+1072),high (tiles+640),high (tiles+656),high (tiles+640),high (tiles+656)
	defb high (tiles+704),high (tiles+688),high (tiles+704),high (tiles+688),high (tiles+704),high (tiles+688),high (tiles+704),high (tiles+688)
	defb high (tiles+704),high (tiles+688),high (tiles+704),high (tiles+688),high (tiles+704),high (tiles+688),high (tiles+704),high (tiles+688)
	defb high (tiles+640),high (tiles+656),high (tiles+640),high (tiles+656),high (tiles+640),high (tiles+656),high (tiles+640),high (tiles+656)
	defb high (tiles+640),high (tiles+656),high (tiles+640),high (tiles+656),high (tiles+640),high (tiles+656),high (tiles+640),high (tiles+656)
	defb high (tiles+512),high (tiles+400),high (tiles+384),high (tiles+528),high (tiles+1088),high (tiles+1104),high (tiles+1120),high (tiles+1136)
	defb high (tiles+1152),high (tiles+1168),high (tiles+1184),high (tiles+1200),high (tiles+1216),high (tiles+1232),high (tiles+1248),high (tiles+1264)
	defb high (tiles+944),high (tiles+528),high (tiles+512),high (tiles+960),high (tiles+1280),high (tiles+1136),high (tiles+1088),high (tiles+1296)
	defb high (tiles+1312),high (tiles+1200),high (tiles+1152),high (tiles+1328),high (tiles+1344),high (tiles+1264),high (tiles+1216),high (tiles+1360)
	defb high (tiles+1376),high (tiles+1392),high (tiles+1408),high (tiles+1424),high (tiles+1424),high (tiles+1408),high (tiles+1440),high (tiles+1456)
	defb high (tiles+1472),high (tiles+1488),high (tiles+1504),high (tiles+1520),high (tiles+1536),high (tiles+1552),high (tiles+1504),high (tiles+1520)
	defb high (tiles+1568),high (tiles+1584),high (tiles+1600),high (tiles+1616),high (tiles+1616),high (tiles+1600),high (tiles+1632),high (tiles+1440)
	defb high (tiles+1648),high (tiles+1456),high (tiles+1536),high (tiles+1552),high (tiles+1552),high (tiles+1536),high (tiles+1536),high (tiles+1504)

; logical code -> tile address, title mode
title_tlo:
	defb low (tiles+0),low (tiles+16),low (tiles+32),low (tiles+48),low (tiles+64),low (tiles+80),low (tiles+96),low (tiles+112)
	defb low (tiles+128),low (tiles+144),low (tiles+160),low (tiles+160),low (tiles+1664),low (tiles+176),low (tiles+192),low (tiles+208)
	defb low (tiles+1680),low (tiles+1696),low (tiles+1712),low (tiles+1728),low (tiles+176),low (tiles+1744),low (tiles+1744),low (tiles+1760)
	defb low (tiles+1776),low (tiles+1792),low (tiles+160),low (tiles+160),low (tiles+1808),low (tiles+176),low (tiles+352),low (tiles+352)
	defb low (tiles+176),low (tiles+1824),low (tiles+1840),low (tiles+1856),low (tiles+1872),low (tiles+1888),low (tiles+1888),low (tiles+1888)
	defb low (tiles+1888),low (tiles+1888),low (tiles+1888),low (tiles+1888),low (tiles+1888),low (tiles+1888),low (tiles+1008),low (tiles+1904)
	defb low (tiles+0),low (tiles+1920),low (tiles+1936),low (tiles+1952),low (tiles+1968),low (tiles+1136),low (tiles+1984),low (tiles+1296)
	defb low (tiles+2000),low (tiles+2016),low (tiles+1088),low (tiles+1280),low (tiles+2032),low (tiles+1104),low (tiles+1120),low (tiles+2048)
	defb low (tiles+2064),low (tiles+2080),low (tiles+304),low (tiles+240),low (tiles+2096),low (tiles+288),low (tiles+2112),low (tiles+496)
	defb low (tiles+2128),low (tiles+2144),low (tiles+2160),low (tiles+2176),low (tiles+2192),low (tiles+2208),low (tiles+320),low (tiles+256)
	defb low (tiles+2224),low (tiles+2240),low (tiles+272),low (tiles+224),low (tiles+480),low (tiles+336),low (tiles+2256),low (tiles+2272)
	defb low (tiles+2288),low (tiles+2304),low (tiles+624),low (tiles+752),low (tiles+768),low (tiles+752),low (tiles+768),low (tiles+800)
	defb low (tiles+816),low (tiles+832),low (tiles+848),low (tiles+864),low (tiles+816),low (tiles+832),low (tiles+848),low (tiles+864)
	defb low (tiles+816),low (tiles+832),low (tiles+848),low (tiles+864),low (tiles+384),low (tiles+400),low (tiles+464),low (tiles+544)
	defb low (tiles+880),low (tiles+896),low (tiles+912),low (tiles+928),low (tiles+880),low (tiles+896),low (tiles+912),low (tiles+928)
	defb low (tiles+880),low (tiles+896),low (tiles+912),low (tiles+928),low (tiles+944),low (tiles+960),low (tiles+560),low (tiles+576)
	defb low (tiles+976),low (tiles+960),low (tiles+400),low (tiles+432),low (tiles+448),low (tiles+432),low (tiles+448),low (tiles+464)
	defb low (tiles+992),low (tiles+1008),low (tiles+816),low (tiles+832),low (tiles+704),low (tiles+688),low (tiles+704),low (tiles+688)
	defb low (tiles+1024),low (tiles+1040),low (tiles+176),low (tiles+176),low (tiles+176),low (tiles+176),low (tiles+176),low (tiles+176)
	defb low (tiles+176),low (tiles+176),low (tiles+1056),low (tiles+1072),low (tiles+640),low (tiles+656),low (tiles+640),low (tiles+656)
	defb low (tiles+704),low (tiles+688),low (tiles+704),low (tiles+688),low (tiles+704),low (tiles+688),low (tiles+704),low (tiles+688)
	defb low (tiles+704),low (tiles+688),low (tiles+704),low (tiles+688),low (tiles+704),low (tiles+688),low (tiles+704),low (tiles+688)
	defb low (tiles+640),low (tiles+656),low (tiles+640),low (tiles+656),low (tiles+640),low (tiles+656),low (tiles+640),low (tiles+656)
	defb low (tiles+640),low (tiles+656),low (tiles+640),low (tiles+656),low (tiles+640),low (tiles+656),low (tiles+640),low (tiles+656)
	defb low (tiles+512),low (tiles+400),low (tiles+384),low (tiles+528),low (tiles+1088),low (tiles+1104),low (tiles+1120),low (tiles+1136)
	defb low (tiles+1152),low (tiles+1168),low (tiles+1184),low (tiles+1200),low (tiles+1216),low (tiles+1232),low (tiles+1248),low (tiles+1264)
	defb low (tiles+944),low (tiles+528),low (tiles+512),low (tiles+960),low (tiles+1280),low (tiles+1136),low (tiles+1088),low (tiles+1296)
	defb low (tiles+1312),low (tiles+1200),low (tiles+1152),low (tiles+1328),low (tiles+1344),low (tiles+1264),low (tiles+1216),low (tiles+1360)
	defb low (tiles+1376),low (tiles+1392),low (tiles+1408),low (tiles+1424),low (tiles+1424),low (tiles+1408),low (tiles+1440),low (tiles+1456)
	defb low (tiles+1472),low (tiles+1488),low (tiles+1504),low (tiles+1520),low (tiles+1536),low (tiles+1552),low (tiles+1504),low (tiles+1520)
	defb low (tiles+1568),low (tiles+1584),low (tiles+1600),low (tiles+1616),low (tiles+1616),low (tiles+1600),low (tiles+1632),low (tiles+1440)
	defb low (tiles+1648),low (tiles+1456),low (tiles+1536),low (tiles+1552),low (tiles+1552),low (tiles+1536),low (tiles+1536),low (tiles+1504)
title_thi:
	defb high (tiles+0),high (tiles+16),high (tiles+32),high (tiles+48),high (tiles+64),high (tiles+80),high (tiles+96),high (tiles+112)
	defb high (tiles+128),high (tiles+144),high (tiles+160),high (tiles+160),high (tiles+1664),high (tiles+176),high (tiles+192),high (tiles+208)
	defb high (tiles+1680),high (tiles+1696),high (tiles+1712),high (tiles+1728),high (tiles+176),high (tiles+1744),high (tiles+1744),high (tiles+1760)
	defb high (tiles+1776),high (tiles+1792),high (tiles+160),high (tiles+160),high (tiles+1808),high (tiles+176),high (tiles+352),high (tiles+352)
	defb high (tiles+176),high (tiles+1824),high (tiles+1840),high (tiles+1856),high (tiles+1872),high (tiles+1888),high (tiles+1888),high (tiles+1888)
	defb high (tiles+1888),high (tiles+1888),high (tiles+1888),high (tiles+1888),high (tiles+1888),high (tiles+1888),high (tiles+1008),high (tiles+1904)
	defb high (tiles+0),high (tiles+1920),high (tiles+1936),high (tiles+1952),high (tiles+1968),high (tiles+1136),high (tiles+1984),high (tiles+1296)
	defb high (tiles+2000),high (tiles+2016),high (tiles+1088),high (tiles+1280),high (tiles+2032),high (tiles+1104),high (tiles+1120),high (tiles+2048)
	defb high (tiles+2064),high (tiles+2080),high (tiles+304),high (tiles+240),high (tiles+2096),high (tiles+288),high (tiles+2112),high (tiles+496)
	defb high (tiles+2128),high (tiles+2144),high (tiles+2160),high (tiles+2176),high (tiles+2192),high (tiles+2208),high (tiles+320),high (tiles+256)
	defb high (tiles+2224),high (tiles+2240),high (tiles+272),high (tiles+224),high (tiles+480),high (tiles+336),high (tiles+2256),high (tiles+2272)
	defb high (tiles+2288),high (tiles+2304),high (tiles+624),high (tiles+752),high (tiles+768),high (tiles+752),high (tiles+768),high (tiles+800)
	defb high (tiles+816),high (tiles+832),high (tiles+848),high (tiles+864),high (tiles+816),high (tiles+832),high (tiles+848),high (tiles+864)
	defb high (tiles+816),high (tiles+832),high (tiles+848),high (tiles+864),high (tiles+384),high (tiles+400),high (tiles+464),high (tiles+544)
	defb high (tiles+880),high (tiles+896),high (tiles+912),high (tiles+928),high (tiles+880),high (tiles+896),high (tiles+912),high (tiles+928)
	defb high (tiles+880),high (tiles+896),high (tiles+912),high (tiles+928),high (tiles+944),high (tiles+960),high (tiles+560),high (tiles+576)
	defb high (tiles+976),high (tiles+960),high (tiles+400),high (tiles+432),high (tiles+448),high (tiles+432),high (tiles+448),high (tiles+464)
	defb high (tiles+992),high (tiles+1008),high (tiles+816),high (tiles+832),high (tiles+704),high (tiles+688),high (tiles+704),high (tiles+688)
	defb high (tiles+1024),high (tiles+1040),high (tiles+176),high (tiles+176),high (tiles+176),high (tiles+176),high (tiles+176),high (tiles+176)
	defb high (tiles+176),high (tiles+176),high (tiles+1056),high (tiles+1072),high (tiles+640),high (tiles+656),high (tiles+640),high (tiles+656)
	defb high (tiles+704),high (tiles+688),high (tiles+704),high (tiles+688),high (tiles+704),high (tiles+688),high (tiles+704),high (tiles+688)
	defb high (tiles+704),high (tiles+688),high (tiles+704),high (tiles+688),high (tiles+704),high (tiles+688),high (tiles+704),high (tiles+688)
	defb high (tiles+640),high (tiles+656),high (tiles+640),high (tiles+656),high (tiles+640),high (tiles+656),high (tiles+640),high (tiles+656)
	defb high (tiles+640),high (tiles+656),high (tiles+640),high (tiles+656),high (tiles+640),high (tiles+656),high (tiles+640),high (tiles+656)
	defb high (tiles+512),high (tiles+400),high (tiles+384),high (tiles+528),high (tiles+1088),high (tiles+1104),high (tiles+1120),high (tiles+1136)
	defb high (tiles+1152),high (tiles+1168),high (tiles+1184),high (tiles+1200),high (tiles+1216),high (tiles+1232),high (tiles+1248),high (tiles+1264)
	defb high (tiles+944),high (tiles+528),high (tiles+512),high (tiles+960),high (tiles+1280),high (tiles+1136),high (tiles+1088),high (tiles+1296)
	defb high (tiles+1312),high (tiles+1200),high (tiles+1152),high (tiles+1328),high (tiles+1344),high (tiles+1264),high (tiles+1216),high (tiles+1360)
	defb high (tiles+1376),high (tiles+1392),high (tiles+1408),high (tiles+1424),high (tiles+1424),high (tiles+1408),high (tiles+1440),high (tiles+1456)
	defb high (tiles+1472),high (tiles+1488),high (tiles+1504),high (tiles+1520),high (tiles+1536),high (tiles+1552),high (tiles+1504),high (tiles+1520)
	defb high (tiles+1568),high (tiles+1584),high (tiles+1600),high (tiles+1616),high (tiles+1616),high (tiles+1600),high (tiles+1632),high (tiles+1440)
	defb high (tiles+1648),high (tiles+1456),high (tiles+1536),high (tiles+1552),high (tiles+1552),high (tiles+1536),high (tiles+1536),high (tiles+1504)

; rtab: one page, the low byte of an address is the row (+ the offset of the table)
rtab:
; +0, +32: draw_buffer address of the row (low, high)
	defb low (draw_buffer+0),low (draw_buffer+40),low (draw_buffer+80),low (draw_buffer+120),low (draw_buffer+160),low (draw_buffer+200),low (draw_buffer+240),low (draw_buffer+280)
	defb low (draw_buffer+320),low (draw_buffer+360),low (draw_buffer+400),low (draw_buffer+440),low (draw_buffer+480),low (draw_buffer+520),low (draw_buffer+560),low (draw_buffer+600)
	defb low (draw_buffer+640),low (draw_buffer+680),low (draw_buffer+720),low (draw_buffer+760),low (draw_buffer+800),low (draw_buffer+840),low (draw_buffer+880),low (draw_buffer+920)
	defb low (draw_buffer+960)
	defs 7
	defb high (draw_buffer+0),high (draw_buffer+40),high (draw_buffer+80),high (draw_buffer+120),high (draw_buffer+160),high (draw_buffer+200),high (draw_buffer+240),high (draw_buffer+280)
	defb high (draw_buffer+320),high (draw_buffer+360),high (draw_buffer+400),high (draw_buffer+440),high (draw_buffer+480),high (draw_buffer+520),high (draw_buffer+560),high (draw_buffer+600)
	defb high (draw_buffer+640),high (draw_buffer+680),high (draw_buffer+720),high (draw_buffer+760),high (draw_buffer+800),high (draw_buffer+840),high (draw_buffer+880),high (draw_buffer+920)
	defb high (draw_buffer+960)
	defs 7
; +64, +96: CGA address of the row (low, high)
	defb low (CGA+0),low (CGA+640),low (CGA+1280),low (CGA+1920),low (CGA+2560),low (CGA+3200),low (CGA+3840),low (CGA+4480)
	defb low (CGA+5120),low (CGA+5760),low (CGA+6400),low (CGA+7040),low (CGA+7680),low (CGA+8320),low (CGA+8960),low (CGA+9600)
	defb low (CGA+10240),low (CGA+10880),low (CGA+11520),low (CGA+12160),low (CGA+12800),low (CGA+13440),low (CGA+14080),low (CGA+14720)
	defb low (CGA+15360)
	defs 7
	defb high (CGA+0),high (CGA+640),high (CGA+1280),high (CGA+1920),high (CGA+2560),high (CGA+3200),high (CGA+3840),high (CGA+4480)
	defb high (CGA+5120),high (CGA+5760),high (CGA+6400),high (CGA+7040),high (CGA+7680),high (CGA+8320),high (CGA+8960),high (CGA+9600)
	defb high (CGA+10240),high (CGA+10880),high (CGA+11520),high (CGA+12160),high (CGA+12800),high (CGA+13440),high (CGA+14080),high (CGA+14720)
	defb high (CGA+15360)
	defs 7
; +128, +160: columns drawn in this frame (first, last; empty when first > last)
; +192, +224: the same of the previous frame (set by flush_screen)
	defs 32,0FFh
	defs 32,0
	defs 32,0FFh
	defs 32,0

; 145 tiles x 16 bytes: (glyph row) x (pixels 0-3, pixels 4-7), EGA mode
tiles:
	defb 037h,0C7h,047h,027h,047h,067h,057h,0A7h,067h,027h,047h,027h,037h,0C7h,007h,007h	; 0: glyph 020h, colour 7
	defb 007h,087h,017h,087h,027h,087h,007h,087h,007h,087h,007h,087h,037h,0E7h,007h,007h	; 1: glyph 021h, colour 7
	defb 037h,0C7h,047h,027h,007h,027h,007h,0C7h,037h,007h,047h,007h,077h,0E7h,007h,007h	; 2: glyph 022h, colour 7
	defb 037h,0C7h,047h,027h,007h,027h,037h,0C7h,007h,027h,047h,027h,037h,0C7h,007h,007h	; 3: glyph 023h, colour 7
	defb 007h,047h,007h,0C7h,017h,047h,027h,047h,077h,0E7h,007h,047h,007h,047h,007h,007h	; 4: glyph 024h, colour 7
	defb 077h,0E7h,047h,007h,077h,087h,007h,047h,007h,027h,047h,047h,037h,087h,007h,007h	; 5: glyph 025h, colour 7
	defb 017h,0C7h,027h,007h,047h,007h,077h,0C7h,047h,027h,047h,027h,037h,0C7h,007h,007h	; 6: glyph 026h, colour 7
	defb 077h,0E7h,047h,027h,007h,047h,007h,087h,017h,007h,017h,007h,017h,007h,007h,007h	; 7: glyph 027h, colour 7
	defb 037h,0C7h,047h,027h,047h,027h,037h,0C7h,047h,027h,047h,027h,037h,0C7h,007h,007h	; 8: glyph 028h, colour 7
	defb 037h,0C7h,047h,027h,047h,027h,037h,0E7h,007h,027h,007h,047h,037h,087h,007h,007h	; 9: glyph 029h, colour 7
	defb 006h,086h,016h,0C6h,036h,0E6h,076h,0F6h,036h,0E6h,016h,0C6h,006h,086h,006h,006h	; 10: glyph 044h, colour 6
	defb 007h,007h,007h,007h,007h,007h,007h,007h,007h,007h,007h,007h,007h,007h,007h,007h	; 11: glyph 000h, colour 7
	defb 002h,012h,002h,032h,002h,072h,002h,0F2h,012h,0F2h,032h,0F2h,072h,0F2h,0F2h,0F2h	; 12: glyph 04Eh, colour 2
	defb 082h,002h,0C2h,002h,0E2h,002h,0F2h,002h,0F2h,082h,0F2h,0C2h,0F2h,0E2h,0F2h,0F2h	; 13: glyph 04Dh, colour 2
	defb 037h,0C7h,047h,027h,047h,007h,037h,0C7h,007h,027h,047h,027h,037h,0C7h,007h,007h	; 14: glyph 013h, colour 7
	defb 017h,0C7h,027h,027h,047h,007h,047h,007h,047h,007h,027h,027h,017h,0C7h,007h,007h	; 15: glyph 003h, colour 7
	defb 017h,087h,027h,047h,047h,027h,047h,027h,047h,027h,027h,047h,017h,087h,007h,007h	; 16: glyph 00Fh, colour 7
	defb 077h,0C7h,047h,027h,047h,027h,077h,0C7h,047h,087h,047h,047h,047h,027h,007h,007h	; 17: glyph 012h, colour 7
	defb 077h,0E7h,047h,007h,047h,007h,077h,087h,047h,007h,047h,007h,077h,0E7h,007h,007h	; 18: glyph 005h, colour 7
	defb 077h,0C7h,027h,027h,027h,027h,037h,0C7h,027h,027h,027h,027h,077h,0C7h,007h,007h	; 19: glyph 002h, colour 7
	defb 047h,027h,067h,027h,057h,027h,047h,0A7h,047h,067h,047h,027h,047h,027h,007h,007h	; 20: glyph 00Eh, colour 7
	defb 047h,027h,047h,027h,047h,027h,047h,027h,047h,027h,047h,027h,037h,0C7h,007h,007h	; 21: glyph 015h, colour 7
	defb 0F2h,0F2h,0F2h,0F2h,0F2h,0F2h,0F2h,0F2h,0F2h,0F2h,0F2h,0F2h,0F2h,0F2h,0F2h,0F2h	; 22: glyph 043h, colour 2
	defb 007h,007h,007h,007h,007h,087h,007h,007h,007h,007h,007h,087h,007h,007h,007h,007h	; 23: glyph 04Fh, colour 7
	defb 002h,002h,002h,072h,002h,072h,002h,072h,002h,002h,072h,072h,072h,072h,072h,072h	; 24: glyph 0FEh, colour 2
	defb 002h,002h,072h,002h,072h,002h,072h,002h,002h,002h,072h,072h,072h,072h,072h,072h	; 25: glyph 0FDh, colour 2
	defb 002h,002h,002h,002h,002h,002h,002h,002h,002h,002h,072h,072h,072h,072h,072h,072h	; 26: glyph 0FCh, colour 2
	defb 002h,002h,002h,072h,002h,072h,002h,072h,002h,002h,072h,002h,072h,002h,072h,002h	; 27: glyph 0F6h, colour 2
	defb 002h,002h,072h,002h,072h,002h,072h,002h,002h,002h,002h,072h,002h,072h,002h,072h	; 28: glyph 0F9h, colour 2
	defb 002h,002h,002h,002h,002h,002h,002h,002h,002h,002h,002h,072h,002h,072h,002h,072h	; 29: glyph 0F8h, colour 2
	defb 037h,0E7h,007h,087h,007h,087h,007h,087h,007h,087h,007h,087h,007h,087h,007h,007h	; 30: glyph 014h, colour 7
	defb 017h,0C7h,027h,027h,047h,007h,047h,0E7h,047h,027h,027h,027h,017h,0C7h,007h,007h	; 31: glyph 007h, colour 7
	defb 002h,002h,002h,072h,002h,072h,002h,072h,002h,002h,002h,072h,002h,072h,002h,072h	; 32: glyph 0FAh, colour 2
	defb 002h,002h,072h,002h,072h,002h,072h,002h,002h,002h,072h,002h,072h,002h,072h,002h	; 33: glyph 0F5h, colour 2
	defb 002h,002h,002h,002h,002h,002h,002h,002h,002h,002h,072h,002h,072h,002h,072h,002h	; 34: glyph 0F4h, colour 2
	defb 002h,002h,002h,072h,002h,072h,002h,072h,002h,002h,002h,002h,002h,002h,002h,002h	; 35: glyph 0F2h, colour 2
	defb 002h,002h,072h,002h,072h,002h,072h,002h,002h,002h,002h,002h,002h,002h,002h,002h	; 36: glyph 0F1h, colour 2
	defb 002h,002h,072h,072h,072h,072h,072h,072h,002h,002h,002h,002h,002h,002h,002h,002h	; 37: glyph 0F3h, colour 2
	defb 004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,004h	; 38: glyph 000h, colour 4
	defb 004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,074h,004h,074h,004h,074h	; 39: glyph 0F8h, colour 4
	defb 004h,004h,004h,074h,004h,074h,004h,074h,004h,004h,074h,004h,074h,004h,074h,004h	; 40: glyph 0F6h, colour 4
	defb 004h,004h,074h,004h,074h,004h,074h,004h,004h,004h,004h,074h,004h,074h,004h,074h	; 41: glyph 0F9h, colour 4
	defb 004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,074h,074h,074h,074h,074h,074h	; 42: glyph 0FCh, colour 4
	defb 004h,004h,074h,004h,074h,004h,074h,004h,004h,004h,074h,074h,074h,074h,074h,074h	; 43: glyph 0FDh, colour 4
	defb 004h,004h,004h,074h,004h,074h,004h,074h,004h,004h,074h,074h,074h,074h,074h,074h	; 44: glyph 0FEh, colour 4
	defb 004h,004h,074h,074h,074h,074h,074h,074h,004h,004h,004h,004h,004h,004h,004h,004h	; 45: glyph 0F3h, colour 4
	defb 004h,004h,074h,004h,074h,004h,074h,004h,004h,004h,004h,004h,004h,004h,004h,004h	; 46: glyph 0F1h, colour 4
	defb 004h,004h,074h,004h,074h,004h,074h,004h,004h,004h,074h,004h,074h,004h,074h,004h	; 47: glyph 0F5h, colour 4
	defb 004h,004h,004h,074h,004h,074h,004h,074h,004h,004h,004h,074h,004h,074h,004h,074h	; 48: glyph 0FAh, colour 4
	defb 004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,074h,004h,074h,004h,074h,004h	; 49: glyph 0F4h, colour 4
	defb 004h,004h,074h,074h,074h,074h,074h,074h,004h,004h,074h,004h,074h,004h,074h,004h	; 50: glyph 0F7h, colour 4
	defb 001h,001h,001h,071h,001h,071h,001h,071h,001h,001h,071h,071h,071h,071h,071h,071h	; 51: glyph 0FEh, colour 1
	defb 001h,001h,071h,001h,071h,001h,071h,001h,001h,001h,071h,071h,071h,071h,071h,071h	; 52: glyph 0FDh, colour 1
	defb 001h,001h,001h,001h,001h,001h,001h,001h,001h,001h,001h,071h,001h,071h,001h,071h	; 53: glyph 0F8h, colour 1
	defb 001h,001h,001h,001h,001h,001h,001h,001h,001h,001h,071h,001h,071h,001h,071h,001h	; 54: glyph 0F4h, colour 1
	defb 001h,001h,071h,071h,071h,071h,071h,071h,001h,001h,001h,071h,001h,071h,001h,071h	; 55: glyph 0FBh, colour 1
	defb 001h,001h,071h,071h,071h,071h,071h,071h,001h,001h,071h,001h,071h,001h,071h,001h	; 56: glyph 0F7h, colour 1
	defb 001h,001h,001h,071h,001h,071h,001h,071h,001h,001h,001h,001h,001h,001h,001h,001h	; 57: glyph 0F2h, colour 1
	defb 001h,001h,071h,001h,071h,001h,071h,001h,001h,001h,001h,001h,001h,001h,001h,001h	; 58: glyph 0F1h, colour 1
	defb 002h,002h,072h,072h,072h,072h,072h,072h,002h,002h,002h,072h,002h,072h,002h,072h	; 59: glyph 0FBh, colour 2
	defb 002h,002h,072h,072h,072h,072h,072h,072h,002h,002h,072h,002h,072h,002h,072h,002h	; 60: glyph 0F7h, colour 2
	defb 022h,042h,022h,042h,072h,0E2h,022h,042h,072h,0E2h,022h,042h,022h,042h,002h,002h	; 61: glyph 063h, colour 2
	defb 0A3h,0A3h,053h,053h,0A3h,0A3h,053h,053h,0A3h,0A3h,053h,053h,0A3h,0A3h,053h,053h	; 62: glyph 0D0h, colour 3
	defb 0A2h,0A2h,052h,052h,0A2h,0A2h,052h,052h,0A2h,0A2h,052h,052h,0A2h,0A2h,052h,052h	; 63: glyph 0D0h, colour 2
	defb 014h,0C4h,014h,0C4h,004h,084h,034h,0E4h,004h,084h,004h,084h,014h,044h,024h,024h	; 64: glyph 0CAh, colour 4
	defb 032h,0C2h,072h,0E2h,0F2h,0F2h,0D2h,0B2h,0F2h,0F2h,0E2h,072h,072h,0E2h,032h,0C2h	; 65: glyph 0CEh, colour 2
	defb 001h,001h,001h,071h,001h,071h,001h,071h,001h,001h,071h,001h,071h,001h,071h,001h	; 66: glyph 0F6h, colour 1
	defb 001h,001h,071h,001h,071h,001h,071h,001h,001h,001h,001h,071h,001h,071h,001h,071h	; 67: glyph 0F9h, colour 1
	defb 003h,003h,003h,073h,003h,073h,003h,073h,003h,003h,003h,073h,003h,073h,003h,073h	; 68: glyph 0FAh, colour 3
	defb 003h,003h,073h,003h,073h,003h,073h,003h,003h,003h,073h,073h,073h,073h,073h,073h	; 69: glyph 0FDh, colour 3
	defb 003h,003h,003h,073h,003h,073h,003h,073h,003h,003h,073h,073h,073h,073h,073h,073h	; 70: glyph 0FEh, colour 3
	defb 003h,003h,073h,003h,073h,003h,073h,003h,003h,003h,073h,003h,073h,003h,073h,003h	; 71: glyph 0F5h, colour 3
	defb 005h,005h,005h,075h,005h,075h,005h,075h,005h,005h,005h,075h,005h,075h,005h,075h	; 72: glyph 0FAh, colour 5
	defb 005h,005h,075h,005h,075h,005h,075h,005h,005h,005h,075h,075h,075h,075h,075h,075h	; 73: glyph 0FDh, colour 5
	defb 005h,005h,005h,075h,005h,075h,005h,075h,005h,005h,075h,075h,075h,075h,075h,075h	; 74: glyph 0FEh, colour 5
	defb 005h,005h,075h,005h,075h,005h,075h,005h,005h,005h,075h,005h,075h,005h,075h,005h	; 75: glyph 0F5h, colour 5
	defb 006h,006h,006h,076h,006h,076h,006h,076h,006h,006h,006h,076h,006h,076h,006h,076h	; 76: glyph 0FAh, colour 6
	defb 006h,006h,076h,006h,076h,006h,076h,006h,006h,006h,076h,076h,076h,076h,076h,076h	; 77: glyph 0FDh, colour 6
	defb 006h,006h,006h,076h,006h,076h,006h,076h,006h,006h,076h,076h,076h,076h,076h,076h	; 78: glyph 0FEh, colour 6
	defb 006h,006h,076h,006h,076h,006h,076h,006h,006h,006h,076h,006h,076h,006h,076h,006h	; 79: glyph 0F5h, colour 6
	defb 003h,003h,073h,073h,073h,073h,073h,073h,003h,003h,003h,073h,003h,073h,003h,073h	; 80: glyph 0FBh, colour 3
	defb 003h,003h,073h,073h,073h,073h,073h,073h,003h,003h,073h,003h,073h,003h,073h,003h	; 81: glyph 0F7h, colour 3
	defb 005h,005h,075h,075h,075h,075h,075h,075h,005h,005h,005h,075h,005h,075h,005h,075h	; 82: glyph 0FBh, colour 5
	defb 005h,005h,075h,075h,075h,075h,075h,075h,005h,005h,075h,005h,075h,005h,075h,005h	; 83: glyph 0F7h, colour 5
	defb 006h,006h,076h,076h,076h,076h,076h,076h,006h,006h,006h,076h,006h,076h,006h,076h	; 84: glyph 0FBh, colour 6
	defb 006h,006h,076h,076h,076h,076h,076h,076h,006h,006h,076h,006h,076h,006h,076h,006h	; 85: glyph 0F7h, colour 6
	defb 006h,016h,006h,036h,006h,076h,006h,0F6h,016h,0F6h,036h,0F6h,076h,0F6h,0F6h,0F6h	; 86: glyph 04Eh, colour 6
	defb 086h,006h,0C6h,006h,0E6h,006h,0F6h,006h,0F6h,086h,0F6h,0C6h,0F6h,0E6h,0F6h,0F6h	; 87: glyph 04Dh, colour 6
	defb 007h,007h,077h,077h,077h,077h,077h,077h,007h,007h,077h,007h,077h,007h,077h,007h	; 88: glyph 0F7h, colour 7
	defb 007h,007h,077h,007h,077h,007h,077h,007h,007h,007h,077h,077h,077h,077h,077h,077h	; 89: glyph 0FDh, colour 7
	defb 007h,007h,077h,077h,077h,077h,077h,077h,007h,007h,007h,007h,007h,007h,007h,007h	; 90: glyph 0F3h, colour 7
	defb 007h,007h,007h,077h,007h,077h,007h,077h,007h,007h,077h,007h,077h,007h,077h,007h	; 91: glyph 0F6h, colour 7
	defb 007h,007h,077h,007h,077h,007h,077h,007h,007h,007h,077h,007h,077h,007h,077h,007h	; 92: glyph 0F5h, colour 7
	defb 007h,007h,077h,007h,077h,007h,077h,007h,007h,007h,007h,077h,007h,077h,007h,077h	; 93: glyph 0F9h, colour 7
	defb 007h,007h,077h,007h,077h,007h,077h,007h,007h,007h,007h,007h,007h,007h,007h,007h	; 94: glyph 0F1h, colour 7
	defb 007h,007h,007h,077h,007h,077h,007h,077h,007h,007h,007h,007h,007h,007h,007h,007h	; 95: glyph 0F2h, colour 7
	defb 007h,007h,007h,007h,007h,007h,007h,007h,007h,007h,077h,007h,077h,007h,077h,007h	; 96: glyph 0F4h, colour 7
	defb 007h,007h,007h,007h,007h,007h,007h,007h,007h,007h,007h,077h,007h,077h,007h,077h	; 97: glyph 0F8h, colour 7
	defb 0F6h,0F6h,076h,0F6h,036h,0F6h,016h,0F6h,006h,0F6h,006h,076h,006h,036h,006h,016h	; 98: glyph 042h, colour 6
	defb 0F6h,0F6h,0F6h,0E6h,0F6h,0C6h,0F6h,086h,0F6h,006h,0E6h,006h,0C6h,006h,086h,006h	; 99: glyph 056h, colour 6
	defb 007h,007h,007h,077h,007h,077h,007h,077h,007h,007h,077h,077h,077h,077h,077h,077h	; 100: glyph 0FEh, colour 7
	defb 007h,007h,077h,077h,077h,077h,077h,077h,007h,007h,007h,077h,007h,077h,007h,077h	; 101: glyph 0FBh, colour 7
	defb 007h,007h,007h,077h,007h,077h,007h,077h,007h,007h,007h,077h,007h,077h,007h,077h	; 102: glyph 0FAh, colour 7
	defb 007h,007h,007h,007h,007h,007h,007h,007h,007h,007h,077h,077h,077h,077h,077h,077h	; 103: glyph 0FCh, colour 7
	defb 007h,007h,007h,007h,007h,007h,007h,007h,0F7h,0F7h,007h,007h,007h,007h,007h,007h	; 104: glyph 078h, colour 7
	defb 007h,007h,007h,007h,007h,007h,007h,007h,007h,0F7h,007h,087h,007h,087h,007h,087h	; 105: glyph 05Ch, colour 7
	defb 007h,007h,007h,007h,007h,007h,007h,007h,0F7h,087h,007h,087h,007h,087h,007h,087h	; 106: glyph 05Dh, colour 7
	defb 007h,087h,007h,087h,007h,087h,007h,087h,007h,0F7h,007h,007h,007h,007h,007h,007h	; 107: glyph 01Ch, colour 7
	defb 007h,087h,007h,087h,007h,087h,007h,087h,0F7h,087h,007h,007h,007h,007h,007h,007h	; 108: glyph 01Dh, colour 7
	defb 007h,087h,007h,087h,007h,087h,007h,087h,007h,087h,007h,087h,007h,087h,007h,087h	; 109: glyph 079h, colour 7
	defb 007h,047h,007h,087h,017h,007h,017h,007h,017h,007h,007h,087h,007h,047h,007h,007h	; 110: glyph 068h, colour 7
	defb 027h,007h,017h,007h,007h,087h,007h,087h,007h,087h,017h,007h,027h,007h,007h,007h	; 111: glyph 069h, colour 7
	defb 007h,007h,007h,007h,007h,007h,007h,007h,007h,007h,017h,087h,017h,087h,007h,007h	; 112: glyph 02Eh, colour 7
	defb 007h,007h,007h,007h,007h,007h,0F7h,0F7h,007h,007h,007h,007h,007h,007h,007h,007h	; 113: glyph 034h, colour 7
	defb 0F7h,0F7h,0F7h,077h,0F7h,077h,0F7h,077h,0D7h,057h,0E7h,037h,0F7h,077h,0F7h,0F7h	; 114: glyph 0C1h, colour 7
	defb 0F7h,0F7h,0F7h,077h,0E7h,037h,0D7h,057h,0F7h,077h,0F7h,077h,0F7h,077h,0F7h,0F7h	; 115: glyph 0C2h, colour 7
	defb 0F7h,0F7h,0F7h,0F7h,0F7h,077h,0F7h,0B7h,087h,017h,0F7h,0B7h,0F7h,077h,0F7h,0F7h	; 116: glyph 0C3h, colour 7
	defb 0F7h,0F7h,0F7h,0F7h,0E7h,0F7h,0D7h,0F7h,087h,017h,0D7h,0F7h,0E7h,0F7h,0F7h,0F7h	; 117: glyph 0C4h, colour 7
	defb 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h	; 118: glyph 000h, colour 0
	defb 003h,003h,073h,003h,073h,003h,073h,003h,003h,003h,003h,003h,003h,003h,003h,003h	; 119: glyph 0F1h, colour 3
	defb 037h,0C7h,047h,027h,007h,027h,007h,0C7h,017h,007h,007h,007h,017h,007h,007h,007h	; 120: glyph 049h, colour 7
	defb 003h,003h,003h,073h,003h,073h,003h,073h,003h,003h,003h,003h,003h,003h,003h,003h	; 121: glyph 0F2h, colour 3
	defb 003h,003h,073h,073h,073h,073h,073h,073h,003h,003h,003h,003h,003h,003h,003h,003h	; 122: glyph 0F3h, colour 3
	defb 003h,003h,003h,003h,003h,003h,003h,003h,003h,003h,073h,003h,073h,003h,073h,003h	; 123: glyph 0F4h, colour 3
	defb 003h,003h,003h,073h,003h,073h,003h,073h,003h,003h,073h,003h,073h,003h,073h,003h	; 124: glyph 0F6h, colour 3
	defb 003h,003h,003h,003h,003h,003h,003h,003h,003h,003h,003h,073h,003h,073h,003h,073h	; 125: glyph 0F8h, colour 3
	defb 003h,003h,073h,003h,073h,003h,073h,003h,003h,003h,003h,073h,003h,073h,003h,073h	; 126: glyph 0F9h, colour 3
	defb 003h,003h,003h,003h,003h,003h,003h,003h,003h,003h,073h,073h,073h,073h,073h,073h	; 127: glyph 0FCh, colour 3
	defb 003h,003h,073h,073h,073h,073h,073h,073h,003h,003h,073h,073h,073h,073h,073h,073h	; 128: glyph 0FFh, colour 3
	defb 007h,007h,007h,007h,007h,007h,077h,0E7h,007h,007h,007h,007h,007h,007h,007h,007h	; 129: glyph 02Ah, colour 7
	defb 017h,087h,027h,047h,047h,027h,077h,0E7h,047h,027h,047h,027h,047h,027h,007h,007h	; 130: glyph 001h, colour 7
	defb 077h,087h,027h,047h,027h,027h,027h,027h,027h,027h,027h,047h,077h,087h,007h,007h	; 131: glyph 004h, colour 7
	defb 077h,0E7h,047h,007h,047h,007h,077h,087h,047h,007h,047h,007h,047h,007h,007h,007h	; 132: glyph 006h, colour 7
	defb 047h,027h,047h,027h,047h,027h,077h,0E7h,047h,027h,047h,027h,047h,027h,007h,007h	; 133: glyph 008h, colour 7
	defb 017h,0C7h,007h,087h,007h,087h,007h,087h,007h,087h,007h,087h,017h,0C7h,007h,007h	; 134: glyph 009h, colour 7
	defb 007h,0E7h,007h,047h,007h,047h,007h,047h,007h,047h,047h,047h,037h,087h,007h,007h	; 135: glyph 00Ah, colour 7
	defb 047h,027h,047h,047h,047h,087h,077h,007h,047h,087h,047h,047h,047h,027h,007h,007h	; 136: glyph 00Bh, colour 7
	defb 047h,007h,047h,007h,047h,007h,047h,007h,047h,007h,047h,007h,077h,0E7h,007h,007h	; 137: glyph 00Ch, colour 7
	defb 047h,027h,067h,067h,057h,0A7h,057h,0A7h,047h,027h,047h,027h,047h,027h,007h,007h	; 138: glyph 00Dh, colour 7
	defb 077h,0C7h,047h,027h,047h,027h,077h,0C7h,047h,007h,047h,007h,047h,007h,007h,007h	; 139: glyph 010h, colour 7
	defb 017h,087h,027h,047h,047h,027h,047h,027h,047h,0A7h,027h,047h,017h,0A7h,007h,007h	; 140: glyph 011h, colour 7
	defb 047h,027h,047h,027h,047h,027h,027h,047h,027h,047h,017h,087h,017h,087h,007h,007h	; 141: glyph 016h, colour 7
	defb 047h,027h,047h,027h,047h,027h,057h,0A7h,057h,0A7h,067h,067h,047h,027h,007h,007h	; 142: glyph 017h, colour 7
	defb 047h,027h,047h,027h,027h,047h,017h,087h,027h,047h,047h,027h,047h,027h,007h,007h	; 143: glyph 018h, colour 7
	defb 027h,027h,027h,027h,027h,027h,017h,0C7h,007h,087h,007h,087h,007h,087h,007h,007h	; 144: glyph 019h, colour 7

; Bt476 palette 0-31: R, G, B (6 bits)
palette:
	defb 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,03Fh
	defb 000h,000h,000h,03Fh,000h,000h,000h,000h,000h,03Fh,000h,03Fh
	defb 000h,000h,000h,000h,03Fh,000h,000h,000h,000h,000h,03Fh,03Fh
	defb 000h,000h,000h,03Fh,03Fh,000h,000h,000h,000h,03Fh,03Fh,03Fh
	defb 000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,03Fh
	defb 000h,000h,000h,03Fh,000h,000h,000h,000h,000h,03Fh,000h,03Fh
	defb 000h,000h,000h,000h,03Fh,000h,000h,000h,000h,000h,03Fh,03Fh
	defb 000h,000h,000h,03Fh,03Fh,000h,000h,000h,000h,03Fh,03Fh,03Fh
palette_end:
