#!/usr/bin/env python3
"""CGA-1V tiles for the SAPI-1 port of Bomberman.

Input: game_table and title_table of orig/bomber.asm (logical code -> MZ-700 display code, attribute) and the
MZ-700 character generator orig/cgrom.bin (512 x 8 bytes, bit 0 is the leftmost pixel, attribute bit 7 selects
the upper 256 characters).

Output: sapi/tables.asm
- tiles: 16 bytes per distinct (display code, attribute) pair, EGA mode of CGA-1V: two bytes per glyph row
  (pixels 0-3, 4-7), high nibble = pixels (D7 left), low nibble = attribute;
- game_tlo/game_thi, title_tlo/title_thi: logical code -> tile address, low and high bytes, one 256-byte page
  each (page aligned); the title mode uses title_table for the codes below 5Ah, game_table for the rest;
- rtab: a page of row tables for flush_screen and draw_addr (draw_buffer and CGA address of each cell row, the
  column ranges to compare);
- palette: Bt476 colours 0-31 (index = attribute * 2 + pixel, COLMASK 1Fh).

The MZ attribute is foreground in bits 6-4 and background in bits 2-0 (bit 0 blue, bit 1 red, bit 2 green). The
game only uses a black background, so the CGA attribute is the MZ foreground colour (0-7).
"""
import os

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.join(here, '..')
src = open(os.path.join(root, 'orig', 'bomber.asm')).read()
cg = open(os.path.join(root, 'orig', 'cgrom.bin'), 'rb').read()
assert len(cg) == 4096


def table(name, entries):
    i = src.index('\n' + name + ':')
    vals = []
    for line in src[i + 1:].splitlines()[1:]:
        line = line.split(';')[0].strip()
        if not line.startswith('defb'):
            break
        vals += [int(x.strip()[:-1], 16) for x in line[4:].split(',')]
    assert len(vals) == 2 * entries, (name, len(vals))
    return [(vals[2 * c], vals[2 * c + 1]) for c in range(entries)]


game = table('game_table', 256)
title = table('title_table', 0x5a)       # title mode uses title_table only for codes below 5Ah

tiles = []                               # list of (display code, attribute)
index = {}


def tile_of(entry):
    code, attr = entry
    assert attr & 0x07 == 0, 'background other than black: %02X' % attr
    key = (code | (attr & 0x80) << 1, (attr >> 4) & 7)
    if key not in index:
        index[key] = len(tiles)
        tiles.append(key)
    return index[key]


game_idx = [tile_of(e) for e in game]
title_idx = [tile_of(e) for e in title]
assert len(tiles) <= 256


def tile_bytes(glyph, colour):
    out = []
    for b in cg[glyph * 8:glyph * 8 + 8]:
        left = sum(((b >> k) & 1) << (7 - k) for k in range(4))
        right = sum(((b >> (4 + k)) & 1) << (7 - k) for k in range(4))
        out += [left | colour, right | colour]
    return out


# MZ-700 colours, Bt476 6 bits per gun
MZ_RGB = [(0, 0, 0), (0, 0, 63), (63, 0, 0), (63, 0, 63), (0, 63, 0), (0, 63, 63), (63, 63, 0), (63, 63, 63)]
palette = []
for a in range(16):
    palette += [(0, 0, 0), MZ_RGB[a & 7]]


def defb(vals, per=16):
    return ['\tdefb ' + ','.join('%03Xh' % v for v in vals[i:i + per]) for i in range(0, len(vals), per)]


def defb_expr(vals, per=8):
    return ['	defb ' + ','.join(vals[i:i + per]) for i in range(0, len(vals), per)]


def tile_addr_tables(name, idx):
    out = ['', '; logical code -> tile address, %s mode' % name, '%s_tlo:' % name]
    out += defb_expr(['low (tiles+%d)' % (16 * t) for t in idx])
    out += ['%s_thi:' % name] + defb_expr(['high (tiles+%d)' % (16 * t) for t in idx])
    return out


ROWS = 25
lines = ['; Generated by tools/make_tables.py from orig/bomber.asm and orig/cgrom.bin - do not edit.', '',
         '	defs (256 - ($ & 0FFh)) & 0FFh  ; the tables below are page aligned']
lines += tile_addr_tables('game', game_idx)
lines += tile_addr_tables('title', title_idx + game_idx[len(title_idx):])
lines += ['', '; rtab: one page, the low byte of an address is the row (+ the offset of the table)',
          'rtab:', '; +0, +32: draw_buffer address of the row (low, high)']
lines += defb_expr(['low (draw_buffer+%d)' % (40 * r) for r in range(ROWS)]) + ['	defs %d' % (32 - ROWS)]
lines += defb_expr(['high (draw_buffer+%d)' % (40 * r) for r in range(ROWS)]) + ['	defs %d' % (32 - ROWS)]
lines += ['; +64, +96: CGA address of the row (low, high)']
lines += defb_expr(['low (CGA+%d)' % (640 * r) for r in range(ROWS)]) + ['	defs %d' % (32 - ROWS)]
lines += defb_expr(['high (CGA+%d)' % (640 * r) for r in range(ROWS)]) + ['	defs %d' % (32 - ROWS)]
lines += ['; +128, +160: columns drawn in this frame (first, last; empty when first > last)',
          '; +192, +224: the same of the previous frame (set by flush_screen)',
          '	defs 32,0FFh', '	defs 32,0', '	defs 32,0FFh', '	defs 32,0', '']
lines += ['; %d tiles x 16 bytes: (glyph row) x (pixels 0-3, pixels 4-7), EGA mode' % len(tiles), 'tiles:']
for n, (glyph, colour) in enumerate(tiles):
    lines += [l + '	; %d: glyph %03Xh, colour %d' % (n, glyph, colour) if i == 0 else l
              for i, l in enumerate(defb(tile_bytes(glyph, colour)))]
lines += ['', '; Bt476 palette 0-31: R, G, B (6 bits)', 'palette:'] + defb([c for rgb in palette for c in rgb], 12)
lines += ['palette_end:', '']
open(os.path.join(root, 'sapi', 'tables.asm'), 'w', newline='\n').write('\n'.join(lines))
print('sapi/tables.asm: %d tiles, %d bytes' % (len(tiles), len(tiles) * 16 + 5 * 256 + 96))
